apiVersion: bigdata.kubernetesbigdataeg.org/v1alpha1
kind: Zookeeper
metadata:
  name: zookeeper-sample
spec:
  # TODO(user): edit the following value to ensure the number 
  # of Pods/Instances your Operand must have on cluster        
  size: 1

  
